GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "comple the course"
}

### 

DELETE http://localhost:3001/todo/delete/64e2575744faeb812a391adc

###

PUT http://localhost:3001/todo/complete/64e255e00fa0b95282739265